from __future__ import annotations

from enum import Enum


class ErrorCode(str, Enum):
    CONFIG_LOAD_FAILED = "CONFIG_LOAD_FAILED"
    ANALYTICS_AGG_FAILED = "ANALYTICS_AGG_FAILED"
    ALPACA_ACCOUNT_FETCH_FAILED = "ALPACA_ACCOUNT_FETCH_FAILED"
    ENGINE_ON_BAR_FAILED = "ENGINE_ON_BAR_FAILED"
    REGIME_CALC_FAILED = "REGIME_CALC_FAILED"
    STRATEGY_ON_BAR_FAILED = "STRATEGY_ON_BAR_FAILED"
    SCANNER_SCAN_FAILED = "SCANNER_SCAN_FAILED"
    RISK_APPLY_FAILED = "RISK_APPLY_FAILED"
    ORDER_SUBMIT_FAILED = "ORDER_SUBMIT_FAILED"
    TRADE_UPDATE_FAILED = "TRADE_UPDATE_FAILED"
    POSITION_UPDATE_FAILED = "POSITION_UPDATE_FAILED"
    POSITION_EXIT_FAILED = "POSITION_EXIT_FAILED"
    RECONCILE_FETCH_FAILED = "RECONCILE_FETCH_FAILED"
    ALPACA_BARS_FETCH_FAILED = "ALPACA_BARS_FETCH_FAILED"
    UW_FLOW_FETCH_FAILED = "UW_FLOW_FETCH_FAILED"
