from __future__ import annotations

from enum import Enum
from typing import Any, Dict, Optional


class CerberusError(Exception):
    """Base exception for all Cerberus errors."""

    def __init__(self, message: str, code: str | ErrorCode, details: Optional[Dict[str, Any]] = None):
        super().__init__(message)
        self.message = message
        self.code = str(code.value) if isinstance(code, Enum) else str(code)
        self.details = details or {}

    def to_dict(self) -> Dict[str, Any]:
        return {
            "error": True,
            "code": self.code,
            "message": self.message,
            "details": self.details,
        }


class ErrorCode(str, Enum):
    # Configuration & Setup
    CONFIG_LOAD_FAILED = "CONFIG_LOAD_FAILED"

    # Analytics & Aggregation
    ANALYTICS_AGG_FAILED = "ANALYTICS_AGG_FAILED"
    REGIME_CALC_FAILED = "REGIME_CALC_FAILED"

    # Alpaca API & Brokerrepository
    ALPACA_ACCOUNT_FETCH_FAILED = "ALPACA_ACCOUNT_FETCH_FAILED"
    ALPACA_BARS_FETCH_FAILED = "ALPACA_BARS_FETCH_FAILED"
    ALPACA_TRADES_FETCH_FAILED = "ALPACA_TRADES_FETCH_FAILED"
    ALPACA_STREAM_ERROR = "ALPACA_STREAM_ERROR"
    ALPACA_CALLBACK_FAILED = "ALPACA_CALLBACK_FAILED"

    # Unusual Whales API
    UW_FLOW_FETCH_FAILED = "UW_FLOW_FETCH_FAILED"

    # Engine & Execution
    ENGINE_ON_BAR_FAILED = "ENGINE_ON_BAR_FAILED"
    CANCEL_ORDERS_FAILED = "CANCEL_ORDERS_FAILED"
    CLOSE_POSITIONS_FAILED = "CLOSE_POSITIONS_FAILED"
    FLATTEN_CONFIRMATION_FAILED = "FLATTEN_CONFIRMATION_FAILED"
    ORDER_EXECUTION_FAILED = "ORDER_EXECUTION_FAILED"

    # Strategy Execution
    STRATEGY_ON_BAR_FAILED = "STRATEGY_ON_BAR_FAILED"

    # Scanner
    SCANNER_SCAN_FAILED = "SCANNER_SCAN_FAILED"
    SCANNER_VALIDATION_FAILED = "SCANNER_VALIDATION_FAILED"
    SCANNER_UNIVERSE_EMPTY = "SCANNER_UNIVERSE_EMPTY"
    FEATURE_PIPELINE_FAILED = "FEATURE_PIPELINE_FAILED"

    # Risk Management
    RISK_APPLY_FAILED = "RISK_APPLY_FAILED"
    RISK_CONFIG_INVALID = "RISK_CONFIG_INVALID"

    # Orders & Positions
    ORDER_SUBMIT_FAILED = "ORDER_SUBMIT_FAILED"
    ORDER_CANCEL_FAILED = "ORDER_CANCEL_FAILED"
    ORDER_CANCEL_ALL_FAILED = "ORDER_CANCEL_ALL_FAILED"
    TRADE_UPDATE_FAILED = "TRADE_UPDATE_FAILED"
    TRADE_UPDATE_PARSE_FAILED = "TRADE_UPDATE_PARSE_FAILED"
    POSITION_UPDATE_FAILED = "POSITION_UPDATE_FAILED"
    POSITION_EXIT_FAILED = "POSITION_EXIT_FAILED"
    RECONCILE_FETCH_FAILED = "RECONCILE_FETCH_FAILED"

    # Main Loop & Agent
    MAIN_LOOP_ERROR = "MAIN_LOOP_ERROR"
    STARTUP_AGENT_FAILED = "STARTUP_AGENT_FAILED"
    EOD_FLATTEN_FAILED = "EOD_FLATTEN_FAILED"
    EOD_AGENT_FAILED = "EOD_AGENT_FAILED"
    AGENT_STAGE2_FAILED = "AGENT_STAGE2_FAILED"
    AGENT_STAGE3_FAILED = "AGENT_STAGE3_FAILED"
    LLM_COMPLETION_FAILED = "LLM_COMPLETION_FAILED"

    # Database
    DATABASE_INIT_FAILED = "DATABASE_INIT_FAILED"
    DATABASE_WRITE_FAILED = "DATABASE_WRITE_FAILED"
    DATABASE_READ_FAILED = "DATABASE_READ_FAILED"
    DATABASE_ROLLBACK = "DATABASE_ROLLBACK"

    # Backtest
    BACKTEST_SCAN_FAILED = "BACKTEST_SCAN_FAILED"
